import type { Grant, BusinessProfile, Goal, Sector } from "./types";

const always = (_p: BusinessProfile) => true;

function limitedCompany(p: BusinessProfile) {
  return p.form === "limited";
}
function sme(p: BusinessProfile) {
  if (p.employees > 249) return false;
  if (p.turnoverEur != null && p.turnoverEur > 50_000_000) return false;
  return true;
}
function microOrSmall(p: BusinessProfile) {
  if (p.employees < 1 || p.employees > 50) return false;
  if (p.turnoverEur != null && p.turnoverEur > 10_000_000) return false;
  return true;
}
function trading6m(p: BusinessProfile) {
  return p.tradingMonths >= 6;
}
function notEi(p: BusinessProfile) {
  return !p.eiClient;
}
function startup18(p: BusinessProfile) {
  return p.stage === "startup" || p.tradingMonths <= 18;
}
function established(p: BusinessProfile) {
  return p.stage === "established" || p.tradingMonths > 18;
}
function exportOrRd(p: BusinessProfile) {
  return p.goals.includes("export") || p.goals.includes("rd") || p.sector === "software" || p.sector === "manufacturing";
}

export const GRANTS: Grant[] = [
  {
    id: "leo-feasibility",
    name: "LEO Feasibility Grant",
    shortName: "Feasibility",
    agency: "Local Enterprise Office",
    category: "Start & validate",
    amountLabel: "Up to €15,000",
    amountMax: 15000,
    coFundRate: 0.5,
    deadlineKind: "rolling",
    deadlineNote: "Open year-round via your county LEO",
    summary:
      "Funds market research, technical assessment, prototyping and testing so you can prove an idea before you spend on it. Rates rise to 60% in Border, Midlands and West.",
    covers: ["Market research", "Consultancy", "Prototyping", "Technical feasibility"],
    nextSteps: [
      "Contact your Local Enterprise Office",
      "Complete a business support request",
      "Submit quotes and a short project plan",
    ],
    documents: ["Project outline", "Quotes for consultants or research", "Financial snapshot"],
    sections: [
      { id: "summary", title: "Project summary", hint: "What you will test and why it matters now." },
      { id: "market", title: "Market evidence", hint: "Who the customer is and how you will learn from them." },
      { id: "budget", title: "Budget", hint: "Itemised costs and the match you will contribute." },
    ],
    winRate: 0.41,
    winBySector: { software: 0.44, food: 0.39, professional: 0.42, manufacturing: 0.4 },
    typicalAward: "€8,000–€12,000",
    difficulty: "straightforward",
    officialUrl: "https://www.localenterprise.ie",
    goals: ["feasibility", "rd", "digital"],
    rules: [
      { id: "sme", label: "Small enterprise in a LEO catchment", test: (p) => p.employees <= 50, knockout: true },
      { id: "not-ei", label: "Not an Enterprise Ireland or IDA client", test: notEi, knockout: true },
      { id: "idea", label: "Early-stage or new product line", test: always },
    ],
  },
  {
    id: "leo-priming",
    name: "LEO Priming Grant",
    shortName: "Priming",
    agency: "Local Enterprise Office",
    category: "Start & validate",
    amountLabel: "Up to €150,000",
    amountMax: 150000,
    coFundRate: 0.5,
    deadlineKind: "rolling",
    deadlineNote: "Evaluated by your LEO approvals committee",
    summary:
      "Capital, salary and development support for businesses in their first 18 months. Typically linked to job creation, with around €15,000 per full-time role.",
    covers: ["Capital equipment", "Salary contributions", "Business development costs"],
    nextSteps: [
      "Confirm eligibility with your LEO",
      "Prepare 3-year projections and job plan",
      "Submit via the LEO application portal",
    ],
    documents: ["Business plan", "3-year financial projections", "CVs of promoters", "Quotes over €5,000"],
    sections: [
      { id: "summary", title: "Business case", hint: "What you are building and the jobs you will create." },
      { id: "market", title: "Market & competition", hint: "Demand, competitors, and why you win locally." },
      { id: "jobs", title: "Employment plan", hint: "Roles, timing, and salaries you will support." },
      { id: "budget", title: "Investment budget", hint: "Eligible costs and your 50% match." },
    ],
    winRate: 0.33,
    winBySector: { food: 0.36, manufacturing: 0.35, retail: 0.28, software: 0.31 },
    typicalAward: "€25,000–€80,000",
    difficulty: "moderate",
    officialUrl: "https://www.localenterprise.ie",
    goals: ["hire", "equipment"],
    rules: [
      { id: "age", label: "Trading 18 months or less", test: startup18, knockout: true },
      { id: "size", label: "Small enterprise, not an EI client", test: (p) => microOrSmall(p) && notEi(p), knockout: true },
      { id: "jobs", label: "Plan to hire or invest in capital", test: (p) => p.goals.includes("hire") || p.goals.includes("equipment") },
    ],
  },
  {
    id: "leo-expansion",
    name: "LEO Business Expansion Grant",
    shortName: "Expansion",
    agency: "Local Enterprise Office",
    category: "Scale locally",
    amountLabel: "Up to €150,000",
    amountMax: 150000,
    coFundRate: 0.5,
    deadlineKind: "rolling",
    deadlineNote: "Open to established LEO clients",
    summary:
      "The primary LEO route for businesses past startup. Covers training, development expenses and salary costs tied to a growth plan.",
    covers: ["Training", "Salary support", "Business development"],
    nextSteps: ["Discuss the growth plan with your LEO mentor", "Compile accounts and quotes", "Apply through the LEO portal"],
    documents: ["Recent accounts", "Growth plan", "Quotes", "Tax clearance"],
    sections: [
      { id: "summary", title: "Growth plan", hint: "What expansion looks like over 12–24 months." },
      { id: "jobs", title: "Team & capability", hint: "Roles you will add or upskill." },
      { id: "budget", title: "Budget", hint: "Eligible spend and match funding." },
    ],
    winRate: 0.35,
    winBySector: { manufacturing: 0.38, food: 0.37, professional: 0.34 },
    typicalAward: "€20,000–€70,000",
    difficulty: "moderate",
    officialUrl: "https://www.localenterprise.ie",
    goals: ["hire", "training", "equipment"],
    rules: [
      { id: "est", label: "Established business (past 18 months)", test: established, knockout: true },
      { id: "leo", label: "Small enterprise, not an EI client", test: (p) => microOrSmall(p) && notEi(p), knockout: true },
    ],
  },
  {
    id: "grow-digital",
    name: "Grow Digital Voucher",
    shortName: "Grow Digital",
    agency: "Local Enterprise Office",
    category: "Digital",
    amountLabel: "Up to €5,000",
    amountMax: 5000,
    coFundRate: 0.5,
    deadlineKind: "rolling",
    deadlineNote: "Requires a Digital for Business project in the last 2 years",
    summary:
      "50% towards off-the-shelf software that is new to the business: CRM, e-commerce, booking, accounting in the cloud, cybersecurity. Does not fund bespoke product development.",
    covers: ["New SaaS subscriptions (one year)", "IT configuration", "Staff training on the tool"],
    nextSteps: [
      "Complete Digital for Business with your LEO if you have not",
      "Choose software recommended in that report",
      "Pay the annual subscription, then claim",
    ],
    documents: ["Digital for Business report", "Software quote/invoice", "Tax clearance"],
    sections: [
      { id: "summary", title: "Digital need", hint: "Which process this software replaces." },
      { id: "tool", title: "Chosen system", hint: "Why this tool, and that it is new to the business." },
      { id: "budget", title: "Costs", hint: "Subscription plus configuration, 50% match." },
    ],
    winRate: 0.62,
    winBySector: { retail: 0.68, professional: 0.64, tourism: 0.66, food: 0.6 },
    typicalAward: "€2,500–€5,000",
    difficulty: "straightforward",
    officialUrl: "https://www.localenterprise.ie/growdigital",
    goals: ["digital"],
    rules: [
      { id: "size", label: "1–50 employees, trading 6+ months", test: (p) => microOrSmall(p) && trading6m(p), knockout: true },
      { id: "not-ei", label: "Not an EI or IDA client", test: notEi, knockout: true },
      { id: "off-shelf", label: "Adopting off-the-shelf software, not building a product", test: always },
    ],
  },
  {
    id: "innovation-voucher",
    name: "Enterprise Ireland Innovation Voucher",
    shortName: "Innovation Voucher",
    agency: "Enterprise Ireland",
    category: "R&D",
    amountLabel: "€10,000 (or €20,000 co-funded)",
    amountMax: 10000,
    coFundRate: 1,
    deadlineKind: "rolling",
    deadlineNote: "Open all year; one active voucher at a time",
    summary:
      "€10,000 of expert time with a university, institute or Technology Gateway to prototype, test technical feasibility, or solve a product challenge. You keep the IP. Company typically pays VAT only on the standard voucher.",
    covers: ["Prototyping", "Technical feasibility", "UX / user research", "New product or process exploration"],
    nextSteps: [
      "Register as a limited company with CRO",
      "Pick a knowledge provider (Technology Gateway, IoT, university)",
      "Apply through the Enterprise Ireland online system",
    ],
    documents: ["Company registration", "Short project brief", "Knowledge provider agreement"],
    sections: [
      { id: "summary", title: "Challenge", hint: "The technical or product question you cannot solve in-house." },
      { id: "provider", title: "Knowledge provider", hint: "Who you will work with and why they fit." },
      { id: "outcomes", title: "Expected outcomes", hint: "Prototype, data, or decision you need in 8–12 weeks." },
    ],
    winRate: 0.71,
    winBySector: { software: 0.74, manufacturing: 0.72, food: 0.69, health: 0.7, green: 0.68 },
    typicalAward: "€10,000 voucher",
    difficulty: "straightforward",
    officialUrl: "https://www.enterprise-ireland.com",
    goals: ["rd", "feasibility", "digital"],
    rules: [
      { id: "ltd", label: "CRO-registered limited company", test: limitedCompany, knockout: true },
      { id: "sme", label: "Fewer than 250 employees / under €50m turnover", test: sme, knockout: true },
    ],
  },
  {
    id: "exploring-innovation",
    name: "Exploring Innovation Grant",
    shortName: "Exploring Innovation",
    agency: "Enterprise Ireland",
    category: "R&D",
    amountLabel: "Up to €35,000",
    amountMax: 35000,
    coFundRate: 0.5,
    deadlineKind: "rolling",
    deadlineNote: "Typical maximum support around €35k",
    summary:
      "Helps companies plan an R&D or innovation project: market research, technical assessment, IP review, and a research strategy before a larger programme.",
    covers: ["Innovation strategy", "IP review", "Technical assessment", "Market research"],
    nextSteps: ["Speak with an EI advisor or LEO about EI client status", "Scope a 3–6 month exploration", "Apply online"],
    documents: ["Project proposal", "Cost breakdown", "Company accounts"],
    sections: [
      { id: "summary", title: "Innovation question", hint: "What you need to know before a full R&D project." },
      { id: "plan", title: "Workplan", hint: "Activities, partners, and 3–6 month timeline." },
      { id: "budget", title: "Budget", hint: "Eligible costs at ~50% support." },
    ],
    winRate: 0.38,
    winBySector: { software: 0.42, manufacturing: 0.4, health: 0.36 },
    typicalAward: "€15,000–€30,000",
    difficulty: "moderate",
    officialUrl: "https://www.enterprise-ireland.com",
    goals: ["rd", "feasibility"],
    rules: [
      { id: "ltd", label: "Limited company with an innovation project", test: limitedCompany, knockout: true },
      { id: "rd", label: "Clear R&D or product exploration need", test: (p) => p.goals.includes("rd") || p.goals.includes("feasibility") },
    ],
  },
  {
    id: "agile-innovation",
    name: "Agile Innovation Fund",
    shortName: "Agile Innovation",
    agency: "Enterprise Ireland",
    category: "R&D",
    amountLabel: "Up to €150,000",
    amountMax: 150000,
    coFundRate: 0.45,
    deadlineKind: "rolling",
    deadlineNote: "Fast-track online application; project cost under €300,000",
    summary:
      "Supports development of new or substantially improved products, services or processes. Built for companies new to R&D or working in short product cycles. Grant rates 25–45% depending on company size.",
    covers: ["Staff costs", "Consultancy", "Materials", "Overheads", "Certification"],
    nextSteps: [
      "Confirm trading and cash resources for the match",
      "Define a scoped product or process project under €300k",
      "Apply via the EI online system (LEO clients can access this too)",
    ],
    documents: ["Project plan", "Costed workstreams", "Evidence of match funding", "Accounts"],
    sections: [
      { id: "summary", title: "Product or process", hint: "What is new or substantially improved." },
      { id: "work", title: "Workstreams", hint: "Build, test, and release plan under 12 months." },
      { id: "team", title: "Team", hint: "Existing and new staff on the project." },
      { id: "budget", title: "Budget", hint: "Eligible costs, grant rate, and cash match." },
    ],
    winRate: 0.29,
    winBySector: { software: 0.34, manufacturing: 0.31, health: 0.27, green: 0.28 },
    typicalAward: "€40,000–€120,000",
    difficulty: "competitive",
    officialUrl: "https://www.enterprise-ireland.com",
    goals: ["rd", "digital"],
    rules: [
      { id: "trading", label: "Established, trading company", test: (p) => p.tradingMonths >= 6, knockout: true },
      { id: "form", label: "Registered Irish company", test: (p) => p.form !== "sole", knockout: true },
      { id: "rd", label: "Building a new or improved product, service or process", test: (p) => p.goals.includes("rd") || p.goals.includes("digital") },
    ],
  },
  {
    id: "digital-discovery",
    name: "Access Advice: Digital Discovery",
    shortName: "Digital Discovery",
    agency: "Enterprise Ireland",
    category: "Digital",
    amountLabel: "Up to €5,000",
    amountMax: 5000,
    coFundRate: 0.8,
    deadlineKind: "rolling",
    deadlineNote: "3–7 days of digital expert time over 8–12 weeks",
    summary:
      "Explore-before-invest support. A digital expert maps AI, data, automation or new systems and leaves you with a 3–12 month action plan. Max daily rate supported €900.",
    covers: ["Digital / AI opportunity assessment", "Systems review", "Implementation roadmap"],
    nextSteps: ["Check manufacturing or internationally traded services eligibility", "Select an approved digital expert", "Apply under Access Advice"],
    documents: ["Short brief", "Company details"],
    sections: [
      { id: "summary", title: "Digital question", hint: "What you want to test before a capital spend." },
      { id: "scope", title: "Focus areas", hint: "AI, ERP, automation, data, or process." },
    ],
    winRate: 0.58,
    winBySector: { manufacturing: 0.62, software: 0.55, food: 0.57 },
    typicalAward: "€3,500–€5,000",
    difficulty: "straightforward",
    officialUrl: "https://www.enterprise-ireland.com",
    goals: ["digital", "rd"],
    rules: [
      { id: "sector", label: "Manufacturing or internationally traded services / HPSU", test: exportOrRd },
      { id: "trading", label: "Irish-based trading business", test: (p) => p.tradingMonths >= 1 },
    ],
  },
  {
    id: "dpi",
    name: "Digital Process Innovation",
    shortName: "Digital Process",
    agency: "Enterprise Ireland",
    category: "Digital",
    amountLabel: "Up to €150,000",
    amountMax: 150000,
    coFundRate: 0.5,
    deadlineKind: "rolling",
    deadlineNote: "For defined operational digitalisation projects",
    summary:
      "Implements new lean-digital processes covering production, delivery or organisational methods. This is a project grant, not a voucher — you need a scoped, costed transformation.",
    covers: ["Process digitalisation", "New delivery methods", "Operational systems"],
    nextSteps: ["Complete discovery first if the scope is unclear", "Build a costed workplan", "Apply as an EI-supported project"],
    documents: ["Process map", "Costed workstreams", "ROI case", "Accounts"],
    sections: [
      { id: "summary", title: "Operational change", hint: "The process that will run differently after the project." },
      { id: "roi", title: "Return", hint: "Time, quality, or cost impact you will measure." },
      { id: "budget", title: "Budget", hint: "Eligible costs at 50% support." },
    ],
    winRate: 0.26,
    winBySector: { manufacturing: 0.32, food: 0.28, software: 0.22 },
    typicalAward: "€50,000–€120,000",
    difficulty: "competitive",
    officialUrl: "https://www.enterprise-ireland.com",
    goals: ["digital"],
    rules: [
      { id: "est", label: "Trading SME with a defined digital process project", test: (p) => p.tradingMonths >= 12 && sme(p), knockout: true },
      { id: "digital", label: "Digital process or operational change in scope", test: (p) => p.goals.includes("digital") },
    ],
  },
  {
    id: "csf",
    name: "Competitive Start Fund",
    shortName: "CSF",
    agency: "Enterprise Ireland",
    category: "Startup equity",
    amountLabel: "Up to €50,000 equity",
    amountMax: 50000,
    coFundRate: 0,
    deadlineKind: "window",
    deadlineNote: "Periodic competitive calls",
    summary:
      "Entry-level Enterprise Ireland equity for early-stage, innovative startups building a product for international markets. Competitive, not a grant.",
    covers: ["Early product development", "Go-to-market", "Founder salaries"],
    nextSteps: ["Confirm innovative, export-oriented product", "Prepare pitch and cap table", "Apply in an open CSF call"],
    documents: ["Pitch deck", "Financial model", "Founder CVs", "Cap table"],
    sections: [
      { id: "summary", title: "Product & market", hint: "What you sell and why it can travel." },
      { id: "team", title: "Team", hint: "Founders, gaps, and advisors." },
      { id: "use", title: "Use of funds", hint: "How €50k moves you to the next round." },
    ],
    winRate: 0.18,
    winBySector: { software: 0.22, health: 0.16, green: 0.17 },
    typicalAward: "€50,000 equity",
    difficulty: "competitive",
    officialUrl: "https://www.enterprise-ireland.com",
    goals: ["rd", "export", "hire"],
    rules: [
      { id: "ltd", label: "Limited company, high-potential startup", test: limitedCompany, knockout: true },
      { id: "age", label: "Early-stage (typically under 3 years)", test: (p) => p.tradingMonths <= 36, knockout: true },
      { id: "export", label: "Innovative product with export ambition", test: (p) => p.goals.includes("export") || p.sector === "software" },
    ],
  },
  {
    id: "pssf",
    name: "Pre-Seed Start Fund",
    shortName: "PSSF",
    agency: "Enterprise Ireland",
    category: "Startup equity",
    amountLabel: "Up to €100,000 CLN",
    amountMax: 100000,
    coFundRate: 0,
    deadlineKind: "rolling",
    deadlineNote: "Via Business Innovation Centres; monthly webinars",
    summary:
      "Convertible loan note of up to €100,000 to cover business-plan development, MVP work, and milestones needed to raise seed in 6–18 months.",
    covers: ["MVP development", "Operating costs", "Investor readiness"],
    nextSteps: ["Engage an Irish BIC", "Attend a PSSF webinar", "Prepare investor-ready plan"],
    documents: ["Business plan", "MVP description", "Founder CVs"],
    sections: [
      { id: "summary", title: "Venture thesis", hint: "Problem, product, and international path." },
      { id: "milestones", title: "6–18 month milestones", hint: "What seed investors will need to see." },
      { id: "use", title: "Use of funds", hint: "How the CLN is spent." },
    ],
    winRate: 0.21,
    winBySector: { software: 0.25, health: 0.2, green: 0.19 },
    typicalAward: "€50,000–€100,000 CLN",
    difficulty: "competitive",
    officialUrl: "https://www.irishbics.ie",
    goals: ["rd", "export", "hire"],
    rules: [
      { id: "ltd", label: "Innovative early-stage limited company", test: (p) => limitedCompany(p) && p.tradingMonths <= 36, knockout: true },
      { id: "ambition", label: "Path to seed funding and export markets", test: (p) => p.goals.includes("export") || p.goals.includes("rd") },
    ],
  },
  {
    id: "market-discovery",
    name: "New Markets Validation Grant",
    shortName: "Market Validation",
    agency: "Enterprise Ireland",
    category: "Export",
    amountLabel: "Up to €150,000",
    amountMax: 150000,
    coFundRate: 0.5,
    deadlineKind: "rolling",
    deadlineNote: "For validating a selected export market",
    summary:
      "Funds structured market research to validate a chosen export market before you commit a full sales push.",
    covers: ["In-market research", "Customer interviews", "Channel mapping"],
    nextSteps: ["Select a target market", "Scope research with an EI advisor", "Apply as an EI-supported project"],
    documents: ["Market hypothesis", "Research plan", "Budget"],
    sections: [
      { id: "summary", title: "Target market", hint: "Country, segment, and why now." },
      { id: "method", title: "Validation method", hint: "How you will talk to real buyers." },
      { id: "budget", title: "Budget", hint: "Travel, research, and specialist costs." },
    ],
    winRate: 0.31,
    winBySector: { food: 0.36, manufacturing: 0.33, software: 0.3 },
    typicalAward: "€20,000–€80,000",
    difficulty: "moderate",
    officialUrl: "https://www.enterprise-ireland.com",
    goals: ["export"],
    rules: [
      { id: "export", label: "Export market in scope", test: (p) => p.goals.includes("export"), knockout: true },
      { id: "trading", label: "Trading company with a product to sell abroad", test: (p) => p.tradingMonths >= 6 },
    ],
  },
  {
    id: "rd-tax",
    name: "R&D Tax Credit",
    shortName: "R&D Tax Credit",
    agency: "Revenue",
    category: "Tax",
    amountLabel: "30% of qualifying R&D",
    amountMax: 500000,
    coFundRate: 0.3,
    deadlineKind: "annual",
    deadlineNote: "Claimed on the corporation tax return",
    summary:
      "A 30% tax credit on qualifying R&D spend. Not a cash grant up front, but one of the most valuable supports once you are building a product. Can be payable in cash in certain cases.",
    covers: ["Qualifying staff costs", "Consumables", "Certain outsourced R&D"],
    nextSteps: ["Map qualifying activities against Revenue guidelines", "Keep contemporaneous records", "Claim via corporation tax return"],
    documents: ["R&D activity narrative", "Timesheets", "Cost schedules"],
    sections: [
      { id: "summary", title: "Technological uncertainty", hint: "What you did not know at the start." },
      { id: "work", title: "Systematic investigation", hint: "How the work was planned and recorded." },
      { id: "costs", title: "Qualifying costs", hint: "Staff, consumables, and subcontractors." },
    ],
    winRate: 0.54,
    winBySector: { software: 0.58, manufacturing: 0.55, health: 0.52 },
    typicalAward: "Depends on spend",
    difficulty: "moderate",
    officialUrl: "https://www.revenue.ie",
    goals: ["rd"],
    rules: [
      { id: "ltd", label: "Company within the charge to Irish corporation tax", test: limitedCompany, knockout: true },
      { id: "rd", label: "Systematic R&D addressing technological uncertainty", test: (p) => p.goals.includes("rd") || p.sector === "software" },
    ],
  },
  {
    id: "seai-sme",
    name: "SEAI SME Energy Upgrade Grants",
    shortName: "SEAI Energy",
    agency: "SEAI",
    category: "Energy",
    amountLabel: "Fixed measures, rapid approval",
    amountMax: 162600,
    coFundRate: 0.3,
    deadlineKind: "rolling",
    deadlineNote: "Immediate approval on selected measures",
    summary:
      "Grants for business energy upgrades including solar PV (non-domestic microgen up to €162,600), solar thermal, fabric, and controls. Some measures now have rapid approval.",
    covers: ["Solar PV", "Solar thermal", "Building fabric", "Heating controls"],
    nextSteps: ["Complete an energy audit if the project is large", "Choose measures", "Apply through SEAI"],
    documents: ["Building details", "Quotes from registered contractors", "BER / energy data if required"],
    sections: [
      { id: "summary", title: "Building & measures", hint: "Site, usage, and the upgrades you will install." },
      { id: "budget", title: "Costs", hint: "Contractor quotes against published grant rates." },
    ],
    winRate: 0.64,
    winBySector: { manufacturing: 0.67, retail: 0.61, tourism: 0.63, food: 0.66 },
    typicalAward: "Depends on measures",
    difficulty: "straightforward",
    officialUrl: "https://www.seai.ie",
    goals: ["energy"],
    rules: [
      { id: "energy", label: "Planning energy or building upgrades", test: (p) => p.goals.includes("energy"), knockout: true },
      { id: "premises", label: "Irish business premises", test: always },
    ],
  },
  {
    id: "green-start",
    name: "GreenStart",
    shortName: "GreenStart",
    agency: "Enterprise Ireland",
    category: "Energy",
    amountLabel: "Up to €5,000",
    amountMax: 5000,
    coFundRate: 0.8,
    deadlineKind: "rolling",
    deadlineNote: "Access Advice assignment with an environmental consultant",
    summary:
      "Introduces environmental best practice and a carbon baseline. Typical assignment ~€6,300 with support up to 80%, capped at €5,000.",
    covers: ["Environmental systems", "Carbon footprint", "Resource reduction plan"],
    nextSteps: ["Become or remain an EI client (or contact LEO if 1–50 manufacturing/ITS)", "Engage a GreenStart consultant", "Apply under Access Advice"],
    documents: ["Carbon calculator output", "Assignment proposal"],
    sections: [
      { id: "summary", title: "Environmental goal", hint: "Waste, energy, or carbon you need to baseline." },
      { id: "scope", title: "Assignment scope", hint: "Days, sites, and deliverables." },
    ],
    winRate: 0.49,
    winBySector: { manufacturing: 0.55, food: 0.52, green: 0.6 },
    typicalAward: "€4,000–€5,000",
    difficulty: "straightforward",
    officialUrl: "https://www.enterprise-ireland.com",
    goals: ["energy"],
    rules: [
      { id: "size", label: "SME or EI client with an environmental project", test: sme },
      { id: "energy", label: "Energy, carbon or resource reduction in scope", test: (p) => p.goals.includes("energy") || p.sector === "green" },
    ],
  },
  {
    id: "skillnet",
    name: "Skillnet Ireland training supports",
    shortName: "Skillnet",
    agency: "Skillnet Ireland",
    category: "People",
    amountLabel: "Subsidised training",
    amountMax: 15000,
    coFundRate: 0.3,
    deadlineKind: "rolling",
    deadlineNote: "Via the relevant sector or regional Skillnet",
    summary:
      "Enterprise-led upskilling. Join a Skillnet network in your sector or region for subsidised courses, often stacked with MentorsWork.",
    covers: ["Management training", "Technical upskilling", "AI / digital courses"],
    nextSteps: ["Find the Skillnet for your sector", "Register the company", "Book funded programmes"],
    documents: ["Company details", "Learner list"],
    sections: [
      { id: "summary", title: "Skills gap", hint: "What the team cannot yet do." },
      { id: "plan", title: "Training plan", hint: "Courses, people, and dates." },
    ],
    winRate: 0.77,
    winBySector: { professional: 0.8, software: 0.76, manufacturing: 0.74 },
    typicalAward: "Course subsidy",
    difficulty: "straightforward",
    officialUrl: "https://www.skillnetireland.ie",
    goals: ["training"],
    rules: [
      { id: "emp", label: "Employer with staff or owner-managers to train", test: (p) => p.employees >= 1 || p.goals.includes("training") },
    ],
  },
  {
    id: "mentorswork",
    name: "MentorsWork",
    shortName: "MentorsWork",
    agency: "Skillnet Ireland",
    category: "People",
    amountLabel: "Fully subsidised 12-week programme",
    amountMax: 0,
    coFundRate: 1,
    deadlineKind: "window",
    deadlineNote: "Cohorts through SFA / Skillnet / Ibec partners",
    summary:
      "Award-winning 12-week programme: one-to-one mentoring, workshops and peer learning. Free to eligible SMEs. Over 3,500 businesses supported.",
    covers: ["Mentoring", "Workshops", "Peer network"],
    nextSteps: ["Register interest at mentorswork.ie", "Select priority areas", "Join the next cohort"],
    documents: ["Short application"],
    sections: [
      { id: "summary", title: "Priorities", hint: "The three business problems you want a mentor on." },
    ],
    winRate: 0.69,
    winBySector: { retail: 0.7, professional: 0.72, food: 0.68 },
    typicalAward: "Programme place",
    difficulty: "straightforward",
    officialUrl: "https://www.mentorswork.ie",
    goals: ["training"],
    rules: [
      { id: "sme", label: "Irish SME", test: sme, knockout: true },
    ],
  },
  {
    id: "leader",
    name: "LEADER / rural enterprise",
    shortName: "LEADER",
    agency: "Pobal / LEADER",
    category: "Rural",
    amountLabel: "Varies by local action group",
    amountMax: 200000,
    coFundRate: 0.5,
    deadlineKind: "window",
    deadlineNote: "Calls run by local action groups",
    summary:
      "Rural development funding for enterprises, community facilities and tourism projects outside the main urban centres. Rules and rates are local.",
    covers: ["Rural enterprise", "Community facilities", "Tourism projects"],
    nextSteps: ["Confirm you are in a LEADER area", "Meet the local action group", "Wait for an open call"],
    documents: ["Local application pack", "Match funding evidence", "Planning if relevant"],
    sections: [
      { id: "summary", title: "Rural impact", hint: "Jobs, visitors, or services the parish gains." },
      { id: "budget", title: "Budget", hint: "Eligible costs against the local rate." },
    ],
    winRate: 0.27,
    winBySector: { tourism: 0.34, food: 0.3, creative: 0.28 },
    typicalAward: "Locally set",
    difficulty: "competitive",
    officialUrl: "https://www.pobal.ie",
    goals: ["equipment", "hire", "feasibility"],
    rules: [
      { id: "region", label: "Project in a rural / LEADER area (not core Dublin)", test: (p) => p.region !== "dublin" },
    ],
  },
  {
    id: "trading-online-legacy",
    name: "Online retail / e-commerce supports",
    shortName: "Online retail",
    agency: "Enterprise Ireland",
    category: "Digital",
    amountLabel: "Scheme-dependent",
    amountMax: 40000,
    coFundRate: 0.5,
    deadlineKind: "window",
    deadlineNote: "Check current Online Retail / digital calls",
    summary:
      "Periodic calls supporting Irish retailers to sell online, improve conversion, and fulfil nationally. Successor activity sits alongside Grow Digital for smaller firms.",
    covers: ["E-commerce platform", "UX", "Digital marketing capability"],
    nextSteps: ["Check if a current retail digital call is open", "Otherwise use Grow Digital for smaller builds"],
    documents: ["Website plan", "Quotes", "Accounts"],
    sections: [
      { id: "summary", title: "Online offer", hint: "What you will sell and to whom." },
      { id: "budget", title: "Build budget", hint: "Platform, content, and launch marketing." },
    ],
    winRate: 0.3,
    winBySector: { retail: 0.38, food: 0.32, tourism: 0.29 },
    typicalAward: "€10,000–€40,000",
    difficulty: "moderate",
    officialUrl: "https://www.enterprise-ireland.com",
    goals: ["digital"],
    rules: [
      { id: "retail", label: "Retail, food or consumer brand selling online", test: (p) => ["retail", "food", "tourism", "creative"].includes(p.sector) },
    ],
  },
  {
    id: "innovation-partnership",
    name: "Innovation Partnership Programme",
    shortName: "Innovation Partnership",
    agency: "Enterprise Ireland",
    category: "R&D",
    amountLabel: "Up to 50% of collaborative R&D",
    amountMax: 200000,
    coFundRate: 0.5,
    deadlineKind: "rolling",
    deadlineNote: "Company + research institute collaboration",
    summary:
      "Collaborative R&D with a university, IoT or Teagasc. Larger and longer than a voucher — for a defined research project with a knowledge partner.",
    covers: ["Collaborative R&D", "Institute researcher time", "Project costs"],
    nextSteps: ["Find a research partner", "Co-write a technical proposal", "Apply jointly"],
    documents: ["Technical proposal", "Partner letter", "Budget", "IP heads of terms"],
    sections: [
      { id: "summary", title: "Research question", hint: "What the partnership will invent or prove." },
      { id: "partner", title: "Institute partner", hint: "Group, PI, and relevant facilities." },
      { id: "ip", title: "IP approach", hint: "How results will be used in the company." },
      { id: "budget", title: "Budget", hint: "Eligible costs and 50% support." },
    ],
    winRate: 0.24,
    winBySector: { manufacturing: 0.28, food: 0.27, health: 0.25, green: 0.26 },
    typicalAward: "€50,000–€150,000",
    difficulty: "competitive",
    officialUrl: "https://www.enterprise-ireland.com",
    goals: ["rd"],
    rules: [
      { id: "ltd", label: "Limited company ready to co-fund research", test: limitedCompany, knockout: true },
      { id: "rd", label: "R&D project that needs an institute partner", test: (p) => p.goals.includes("rd") },
    ],
  },
  {
    id: "gradstart",
    name: "GradStart",
    shortName: "GradStart",
    agency: "Enterprise Ireland",
    category: "People",
    amountLabel: "Up to €15,000 per year",
    amountMax: 30000,
    coFundRate: 0.5,
    deadlineKind: "rolling",
    deadlineNote: "Two-year graduate contract support",
    summary:
      "Up to €15,000 per year (or 50% of salary, whichever is lower) toward hiring a graduate on a two-year contract.",
    covers: ["Graduate salary contribution"],
    nextSteps: ["Identify a graduate role", "Confirm EI client pathway", "Apply around the hire"],
    documents: ["Role spec", "Salary details", "Graduate CV"],
    sections: [
      { id: "summary", title: "Role", hint: "What the graduate will own in year one." },
      { id: "budget", title: "Salary", hint: "Gross salary and the 50% / €15k cap." },
    ],
    winRate: 0.4,
    winBySector: { software: 0.44, professional: 0.41, manufacturing: 0.38 },
    typicalAward: "€15,000/year",
    difficulty: "moderate",
    officialUrl: "https://www.enterprise-ireland.com",
    goals: ["hire"],
    rules: [
      { id: "hire", label: "Planning to hire a graduate", test: (p) => p.goals.includes("hire") },
      { id: "est", label: "Established employer", test: (p) => p.employees >= 1 && p.tradingMonths >= 6 },
    ],
  },
  {
    id: "climate-voucher",
    name: "Climate Action Voucher",
    shortName: "Climate Voucher",
    agency: "Enterprise Ireland",
    category: "Energy",
    amountLabel: "Voucher for climate action planning",
    amountMax: 9000,
    coFundRate: 0.8,
    deadlineKind: "rolling",
    deadlineNote: "Check current EI climate offers",
    summary:
      "Short, expert-led climate action support so SMEs can plan decarbonisation before a capital project. Pair with SEAI measures once the plan exists.",
    covers: ["Climate action plan", "Emissions baseline", "Measure shortlist"],
    nextSteps: ["Run Climate Toolkit 4 Business", "Apply for the voucher", "Sequence SEAI capital after"],
    documents: ["Toolkit output", "Assignment proposal"],
    sections: [
      { id: "summary", title: "Climate starting point", hint: "Sites, fuels, and what you already measure." },
    ],
    winRate: 0.46,
    winBySector: { manufacturing: 0.5, food: 0.48, green: 0.55 },
    typicalAward: "€5,000–€9,000",
    difficulty: "straightforward",
    officialUrl: "https://www.enterprise-ireland.com",
    goals: ["energy"],
    rules: [
      { id: "energy", label: "Decarbonisation or climate planning in scope", test: (p) => p.goals.includes("energy") || p.sector === "green" },
    ],
  },
  {
    id: "creative-ireland",
    name: "Creative Ireland / Arts Council project funds",
    shortName: "Creative funds",
    agency: "Arts Council",
    category: "Creative",
    amountLabel: "Project-dependent",
    amountMax: 80000,
    coFundRate: 0.8,
    deadlineKind: "window",
    deadlineNote: "Periodic strategic and project calls",
    summary:
      "Project funding for creative practice, festivals, and cultural enterprises. Competitive and deadline-driven. Not a substitute for LEO priming.",
    covers: ["Project costs", "Artist fees", "Production"],
    nextSteps: ["Read the current Arts Council or Creative Ireland call", "Align to the published themes", "Apply in the window"],
    documents: ["Artistic proposal", "Budget", "Track record"],
    sections: [
      { id: "summary", title: "Artistic proposition", hint: "The work, audience, and public value." },
      { id: "budget", title: "Budget", hint: "Fees, production, and match." },
    ],
    winRate: 0.22,
    winBySector: { creative: 0.28, tourism: 0.18 },
    typicalAward: "€5,000–€40,000",
    difficulty: "competitive",
    officialUrl: "https://www.artscouncil.ie",
    goals: ["feasibility"],
    rules: [
      { id: "creative", label: "Creative, cultural or festival activity", test: (p) => p.sector === "creative" || p.sector === "tourism" },
    ],
  },
  {
    id: "dfb",
    name: "Digital for Business",
    shortName: "Digital for Business",
    agency: "Local Enterprise Office",
    category: "Digital",
    amountLabel: "Free digital assessment",
    amountMax: 2700,
    coFundRate: 1,
    deadlineKind: "rolling",
    deadlineNote: "Gateway to the Grow Digital Voucher",
    summary:
      "Free consultancy that scores digital maturity and recommends tools. Completing it in the last two years is required before a Grow Digital Voucher.",
    covers: ["Digital audit", "Roadmap", "Software recommendations"],
    nextSteps: ["Book Digital for Business with your LEO", "Implement quick wins", "Apply for Grow Digital if software is needed"],
    documents: ["None to start"],
    sections: [
      { id: "summary", title: "Current stack", hint: "Tools you already pay for and the gaps." },
    ],
    winRate: 0.81,
    winBySector: { retail: 0.84, professional: 0.8, food: 0.79 },
    typicalAward: "Funded consultancy",
    difficulty: "straightforward",
    officialUrl: "https://www.localenterprise.ie",
    goals: ["digital"],
    rules: [
      { id: "leo", label: "Small enterprise, not an EI client", test: (p) => microOrSmall(p) && notEi(p), knockout: true },
    ],
  },
];

export const CATALOGUE_REVIEWED_AT = "2026-09-06";
export const CATALOGUE_TIER = "prototype" as const;

export function getGrant(id: string) {
  return GRANTS.find((g) => g.id === id);
}

export const SECTOR_LABELS: Record<Sector, string> = {
  software: "Software & digital",
  manufacturing: "Manufacturing",
  food: "Food & drink",
  professional: "Professional services",
  retail: "Retail",
  green: "Climate & energy",
  tourism: "Tourism & hospitality",
  creative: "Creative & culture",
  health: "Health & medtech",
  construction: "Construction",
};

export const GOAL_LABELS: Record<Goal, string> = {
  hire: "Hiring",
  equipment: "Equipment / capital",
  digital: "Digital tools",
  export: "Export",
  rd: "Product / R&D",
  energy: "Energy & climate",
  training: "Training",
  feasibility: "Feasibility / research",
};

export const REGION_LABELS: Record<string, string> = {
  dublin: "Dublin",
  cork: "Cork",
  galway: "Galway",
  limerick: "Limerick",
  bmw: "Border, Midlands & West",
  other: "Rest of Ireland",
};
