/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as GrantsRouteImport } from './routes/grants'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MatchRouteImport } from './routes/match'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as StandRouteImport } from './routes/stand'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as GrantsIdRouteImport } from './routes/grants_.$id'
import { Route as PipelineIdRouteImport } from './routes/pipeline_.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PipelineIdPrintRouteImport } from './routes/pipeline_.$id_.print'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsRoute = GrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const StandRoute = StandRouteImport.update({
  id: '/stand',
  path: '/stand',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsIdRoute = GrantsIdRouteImport.update({
  id: '/grants_/$id',
  path: '/grants/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineIdRoute = PipelineIdRouteImport.update({
  id: '/pipeline_/$id',
  path: '/pipeline/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineIdPrintRoute = PipelineIdPrintRouteImport.update({
  id: '/pipeline_/$id_/print',
  path: '/pipeline/$id/print',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/grants': typeof GrantsRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/pipeline': typeof PipelineRoute
  '/privacy': typeof PrivacyRoute
  '/stand': typeof StandRoute
  '/terms': typeof TermsRoute
  '/grants/$id': typeof GrantsIdRoute
  '/pipeline/$id': typeof PipelineIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pipeline/$id/print': typeof PipelineIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/grants': typeof GrantsRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/pipeline': typeof PipelineRoute
  '/privacy': typeof PrivacyRoute
  '/stand': typeof StandRoute
  '/terms': typeof TermsRoute
  '/grants/$id': typeof GrantsIdRoute
  '/pipeline/$id': typeof PipelineIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pipeline/$id/print': typeof PipelineIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/grants': typeof GrantsRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/match': typeof MatchRoute
  '/pipeline': typeof PipelineRoute
  '/privacy': typeof PrivacyRoute
  '/stand': typeof StandRoute
  '/terms': typeof TermsRoute
  '/grants_/$id': typeof GrantsIdRoute
  '/pipeline_/$id': typeof PipelineIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/pipeline_/$id_/print': typeof PipelineIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/grants'
    | '/intelligence'
    | '/login'
    | '/match'
    | '/pipeline'
    | '/privacy'
    | '/stand'
    | '/terms'
    | '/grants/$id'
    | '/pipeline/$id'
    | '/api/auth/$'
    | '/pipeline/$id/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/grants'
    | '/intelligence'
    | '/login'
    | '/match'
    | '/pipeline'
    | '/privacy'
    | '/stand'
    | '/terms'
    | '/grants/$id'
    | '/pipeline/$id'
    | '/api/auth/$'
    | '/pipeline/$id/print'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/grants'
    | '/intelligence'
    | '/login'
    | '/match'
    | '/pipeline'
    | '/privacy'
    | '/stand'
    | '/terms'
    | '/grants_/$id'
    | '/pipeline_/$id'
    | '/api/auth/$'
    | '/pipeline_/$id_/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  GrantsRoute: typeof GrantsRoute
  IntelligenceRoute: typeof IntelligenceRoute
  LoginRoute: typeof LoginRoute
  MatchRoute: typeof MatchRoute
  PipelineRoute: typeof PipelineRoute
  PrivacyRoute: typeof PrivacyRoute
  StandRoute: typeof StandRoute
  TermsRoute: typeof TermsRoute
  GrantsIdRoute: typeof GrantsIdRoute
  PipelineIdRoute: typeof PipelineIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  PipelineIdPrintRoute: typeof PipelineIdPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants': {
      id: '/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof GrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stand': {
      id: '/stand'
      path: '/stand'
      fullPath: '/stand'
      preLoaderRoute: typeof StandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants_/$id': {
      id: '/grants_/$id'
      path: '/grants/$id'
      fullPath: '/grants/$id'
      preLoaderRoute: typeof GrantsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline_/$id': {
      id: '/pipeline_/$id'
      path: '/pipeline/$id'
      fullPath: '/pipeline/$id'
      preLoaderRoute: typeof PipelineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline_/$id_/print': {
      id: '/pipeline_/$id_/print'
      path: '/pipeline/$id/print'
      fullPath: '/pipeline/$id/print'
      preLoaderRoute: typeof PipelineIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  GrantsRoute: GrantsRoute,
  IntelligenceRoute: IntelligenceRoute,
  LoginRoute: LoginRoute,
  MatchRoute: MatchRoute,
  PipelineRoute: PipelineRoute,
  PrivacyRoute: PrivacyRoute,
  StandRoute: StandRoute,
  TermsRoute: TermsRoute,
  GrantsIdRoute: GrantsIdRoute,
  PipelineIdRoute: PipelineIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  PipelineIdPrintRoute: PipelineIdPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
